#!/bin/sh

# Script to speed up the process of starting a new project

LOCATION=$HOME"/Projects/"$2

# Break if nothing
if [ $# -le 1 ]; then
    echo "Not enough paramaters!"
    exit 1
fi

# Create a cpp project
if [ $1 == "cpp" ]; then
    mkdir -p $LOCATION
    mkdir -p $LOCATION"/src"
    mkdir -p $LOCATION"/include"

    cp $HOME/.config/vim-snippets/skeleton.main.cmake $LOCATION/CmakeLists.txt
    cp $HOME/.config/vim-snippets/skeleton.main.c $LOCATION/src/main.cpp
fi

# Create a Python Project

# Create a C Project

# Create a Rust Project

# Create a C# Project

# Create a Java Project

# Create a Go Project

# Create a Script
if [ $1 == "script" ]; then
    LOCATION=$HOME/.config/scripts
    touch $LOCATION/$2
    echo '#!/bin/sh' >> $LOCATION/$2
fi

# ...

# Project info
echo $1" >>> "$LOCATION
